### ISSUE TITLE
bug: update to Prettier 3.0

### ISSUE THREAD

**Issue by recallwei** [vuejs/eslint-config-prettier#16] opened 2023-07-06 08:07 UTC
`prettier.resolveConfig.sync` is removed in Prettier 3.0. 

![image](https://github.com/vuejs/eslint-config-prettier/assets/62941121/4fcb534d-c284-4bfc-9b98-c80c744be83d)

**Comment by gewisser** [comment] 2023-07-06 09:13
+

**Comment by sk-tjdownes** [comment] 2023-07-06 20:05
Not a bug, but a needed enhancement for sure. +1

**Comment by logue** [comment] 2023-07-07 06:41
Although it is a temporary measure, it now works by explicitly specifying the newer `eslint-plugin-prettier` version in `package.json` `resolutions`.

```json
  "resolutions": {
    "eslint-plugin-prettier": "^5.0.0-alpha.1"
  }
```

**Comment by lvzhenbo** [comment] 2023-07-12 01:43
eslint-plugin-prettier has been officially released with [5.0.0](https://github.com/prettier/eslint-plugin-prettier/releases/tag/v5.0.0) support for prettier3

**Comment by francoism90** [comment] 2023-07-13 19:51
@logue I tried the workaround, but it doesn't anything, stil lthe same error.

Any other workarounds?

**Comment by sim-kou** [comment] 2023-07-17 16:51
> Although it is a temporary measure, it now works by explicitly specifying the newer `eslint-plugin-prettier` version in `package.json` `resolutions`.
> 
> ```json
>   "resolutions": {
>     "eslint-plugin-prettier": "^5.0.0-alpha.2"
>   }
> ```

Or with npm 8.3+ (see the [doc](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#overrides)):
```json
"overrides": {
  "eslint-plugin-prettier": "^5.0.0"
}
```

**Closed** 2023-07-20 13:30 UTC
